T242459: Fix initialization parameter for superclass in PerfactUserwarning
perfact/Products.PerFactErrors pull request #5
Opened 2023-06-22 12:46 UTC by tjastrzembski

@viktordick As we talked about earlier, I prepared a small PR for this finding. 

However the actual behavior on apperrorlog parameter does not change, because PerFactException initializes it defaultly as False anyway. 

I also removed apperrorlog as possible key word argument to prevent taking it twice as parameter.
What do you think? Will we change the intended/lived behavior by this?

2023-06-22 13:06 UTC, viktordick requested changes
I don't like this solution.

If `PerFactUserWarning` sets some defaults for `PerFactException`, it should still allow to override some of them. With this, if someone passes `apperrorlog`, it is ignored.

It would be better to create a default dictionary, update it with everything from `**kw` and then pass that.

2023-06-22 13:55 UTC, tjastrzembski commented
I am not quite sure if I understand it correct. Also with you approach reg. the default dictionary, we would still allow to override params like `show_to_user` or `apperrorlog`, if we take them. 

I just ask, if this is our intention to allow it or to restrict it in this case.

2023-07-03 08:21 UTC, tjastrzembski commented
@viktordick As we clarified earlier I reverted the commit, so the UserWarning really is used as pure UserWarning (without turning off visibility to user or adding it to ErrorLog). 

So the consequence is now, that using parameter `apperrorlog` will lead to error now (similar to `show_to_user`).

In case of displaying it into Error Log we should use PerFactException which provides this flexibility then.

2023-07-05 12:00 UTC, viktordick approved these changes
LGTM

2023-07-05 12:00 UTC, merged